name: Commit Lint

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pnpm install
      - name: Run commitlint
        run: npx commitlint --from HEAD~10 --to HEAD
